/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.learning.kotlin

fun main() {
    // Chaining lets
    var a = 1
    var b= 2

    a = a.let { it + 2 }.let { it + b }
    println(a)

    // Null checking let
    var name : String? = "Kotlin let null check"
    name?.let { println("I should not print") }
    name = null
    name?.let { println("I should print") }

    // Combining let and run
    var someString : String? = null
    someString?.let { println("String is defined") } ?: run {
        println("String was null. Setting default value to Kotlin")
        someString = "Kotlin"
    }
    println(someString)

    // Let vs also (Quiz time)
    var person = Person("Kotlin", "People")

    var withLet = person.let { it.type = "Kuties" }
    var withAlso = person.also { it.type = "Kuties" }

    println(withLet)
    println(withAlso)

    // Run vs apply vs also
    val password = PasswordGenerator().run {
        seed = "overriddenSeed"
        hash = { str: String -> "overriddenHash $str"}
        repetition= 5
        generate()
    }
    println(password)

    val generator = PasswordGenerator().apply {
        seed = "someString"
        repetition = 1000
    }
    println(generator.generate())

    val alsoGenerator = PasswordGenerator().also {
        println("The seed is ${it.seed}")
    }.generate()
    println(alsoGenerator)
}

class PasswordGenerator {
    var seed: String = "initialSeed"
    var hash: (string: String) -> String = { str: String -> "someHash-$str"}
    var repetition: Int = 10

    fun generate(): String {
        return "${hash(seed)} repeating $repetition times"
    }
}
data class Person(var name : String? = null, var type : String? = null)
